### ISSUE TITLE
Part 1 - Ready Player One - where to put Player.swift

### ISSUE THREAD

**Issue by denisenepraunig** [nicklockwood/RetroRampage#1]
Hello Nick,

in Part 1 - Ready Player One - you say you should create a new Player.swift file.

You didn't specify the location. I put it inside Engine after looking at the provided source code.

Just a tiny thing I stumbled upon 🙂. I am really enjoying your tutorial so far - thank you very much!

BR Denise

**Comment by nicklockwood** [comment]
Thanks, I'll add a clarification 👍

**Comment by nicklockwood** [comment]
Fixed. Thanks again!
